// ═══════════════════════════════════════════════════════════
// 뜨온 — Template & Level Data
// Carol Gray Social Stories™ 10.4 기준
// ═══════════════════════════════════════════════════════════

const TYPES = {
  desc:   { label: '설명문',     cls: 'b-desc',   color: '#3a7ca5', desc: '사실, 상황/배경 서술' },
  persp:  { label: '조망문',     cls: 'b-persp',  color: '#8b6bab', desc: '타인의 생각/감정/반응' },
  coach:  { label: '코칭문',     cls: 'b-coach',  color: '#c97b3c', desc: '시도할 수 있는 행동 안내' },
  affirm: { label: '긍정확인문', cls: 'b-affirm', color: '#c9a138', desc: '학습자의 강점/안전 확인' },
};

const FUNCTIONS = ['전체', '실물획득', '관심끌기', '회피/탈출', '감각자극'];

const TEMPLATES = [
  { id:'wait-turn', icon:'✋', name:'차례 기다리기', desc:'활동·대화에서 자기 차례를 기다리는 상황', fn:'실물획득 / 관심끌기',
    gen:(n)=>[
      {type:'desc',text:`학교에서는 여러 친구들이 함께 생활합니다.`},
      {type:'desc',text:`활동을 할 때 모든 사람이 한꺼번에 할 수 없을 때가 있습니다.`},
      {type:'desc',text:`그럴 때 사람들은 차례를 정해서 한 명씩 합니다.`},
      {type:'persp',text:`차례를 기다리면 다른 친구들은 '공정하다'고 느낍니다.`},
      {type:'persp',text:`선생님도 차례를 잘 기다리는 모습을 보면 기쁘게 생각합니다.`},
      {type:'desc',text:`${n}도 차례를 기다려야 할 때가 있습니다.`},
      {type:'coach',text:`${n}은(는) 차례를 기다릴 때 손을 무릎 위에 올려놓고 기다려 볼 수 있습니다.`},
      {type:'affirm',text:`기다리는 것은 연습하면 점점 더 쉬워질 수 있습니다.`},
      {type:'desc',text:`차례가 오면 ${n}도 할 수 있습니다.`},
      {type:'affirm',text:`차례를 기다리는 것은 괜찮은 일입니다.`},
    ] },
  { id:'ask-help', icon:'🙋', name:'도움 요청하기', desc:'어려운 과제·상황에서 적절히 도움을 요청', fn:'회피/탈출',
    gen:(n)=>[
      {type:'desc',text:`학교에서 공부를 할 때 어려운 것이 있을 수 있습니다.`},
      {type:'desc',text:`모르는 것이 있는 것은 자연스러운 일입니다.`},
      {type:'persp',text:`어려운 문제를 만나면 답답하거나 화가 날 수 있습니다.`},
      {type:'desc',text:`그럴 때 선생님이나 친구에게 도움을 요청할 수 있습니다.`},
      {type:'coach',text:`${n}은(는) 어려울 때 손을 들거나 "도와주세요"라고 말해 볼 수 있습니다.`},
      {type:'coach',text:`도움 요청 카드를 선생님 책상 위에 올려놓는 방법을 사용해 볼 수도 있습니다.`},
      {type:'persp',text:`선생님은 ${n}이(가) 도움을 요청하면 기꺼이 도와주려고 합니다.`},
      {type:'desc',text:`도움을 받으면 어려운 문제도 해결할 수 있습니다.`},
      {type:'affirm',text:`도움을 요청하는 것은 용기 있는 행동입니다.`},
      {type:'affirm',text:`${n}은(는) 도움을 요청하는 연습을 하고 있습니다.`},
    ] },
  { id:'transition', icon:'🔄', name:'활동 전환하기', desc:'활동을 멈추고 다음 활동으로 넘어가기', fn:'회피/탈출 / 실물획득',
    gen:(n)=>[
      {type:'desc',text:`학교에서는 하루 동안 여러 가지 활동을 합니다.`},
      {type:'desc',text:`한 가지 활동이 끝나면 다음 활동으로 바뀝니다.`},
      {type:'desc',text:`좋아하는 활동이 끝나야 할 때도 있습니다.`},
      {type:'persp',text:`좋아하는 것을 그만두어야 할 때 아쉽거나 속상한 마음이 들 수 있습니다.`},
      {type:'desc',text:`이런 마음이 드는 것은 자연스러운 일입니다.`},
      {type:'coach',text:`${n}은(는) 선생님이 "정리하세요"라고 하면 하던 것을 천천히 멈추어 볼 수 있습니다.`},
      {type:'coach',text:`다음 활동이 무엇인지 일과표를 확인해 볼 수 있습니다.`},
      {type:'persp',text:`선생님과 친구들은 ${n}이(가) 잘 전환하면 함께 활동할 수 있어서 좋다고 느낍니다.`},
      {type:'affirm',text:`활동이 바뀌어도 나중에 좋아하는 활동을 다시 할 수 있는 시간이 있습니다.`},
      {type:'affirm',text:`${n}은(는) 활동을 바꾸는 연습을 하고 있고, 점점 나아지고 있습니다.`},
    ] },
  { id:'gentle-body', icon:'🤝', name:'친구 존중하기 (신체)', desc:'부드러운 몸으로 친구를 대하기', fn:'관심끌기 / 감각자극',
    gen:(n)=>[
      {type:'desc',text:`학교에는 많은 친구들이 함께 있습니다.`},
      {type:'desc',text:`친구들과 가까이 있을 때 몸이 부딪힐 수 있습니다.`},
      {type:'persp',text:`친구를 세게 만지거나 밀면 친구는 아프거나 무섭다고 느낄 수 있습니다.`},
      {type:'persp',text:`친구가 아프면 같이 놀고 싶지 않다고 생각할 수 있습니다.`},
      {type:'desc',text:`사람들은 서로의 몸을 부드럽게 대합니다.`},
      {type:'coach',text:`${n}은(는) 친구 옆을 지나갈 때 천천히 걸어 볼 수 있습니다.`},
      {type:'coach',text:`친구에게 이야기하고 싶을 때 어깨를 가볍게 톡톡 치거나 이름을 불러 볼 수 있습니다.`},
      {type:'persp',text:`부드럽게 하면 친구들은 안전하다고 느끼고 ${n}과(와) 같이 놀고 싶어 합니다.`},
      {type:'affirm',text:`부드러운 몸을 쓰는 것은 연습할 수 있는 기술입니다.`},
      {type:'affirm',text:`${n}은(는) 친구들과 안전하게 지내는 방법을 배우고 있습니다.`},
    ] },
  { id:'loud-voice', icon:'🔊', name:'목소리 크기 조절', desc:'상황에 맞는 목소리 크기 사용', fn:'감각자극 / 관심끌기',
    gen:(n)=>[
      {type:'desc',text:`사람들은 장소에 따라 다른 크기의 목소리를 사용합니다.`},
      {type:'desc',text:`교실에서는 보통 작은 목소리나 보통 목소리를 사용합니다.`},
      {type:'desc',text:`운동장에서는 큰 목소리를 사용해도 괜찮습니다.`},
      {type:'persp',text:`교실에서 큰 목소리를 내면 친구들이 깜짝 놀라거나 집중하기 어려울 수 있습니다.`},
      {type:'persp',text:`선생님은 교실에서 작은 목소리를 쓰면 고맙다고 느낍니다.`},
      {type:'coach',text:`${n}은(는) 교실에서 이야기할 때 작은 목소리로 말해 볼 수 있습니다.`},
      {type:'desc',text:`작은 목소리란 옆에 있는 사람만 들을 수 있는 크기입니다.`},
      {type:'coach',text:`큰 소리를 내고 싶을 때는 "운동장에서 하자"라고 스스로에게 말해 볼 수 있습니다.`},
      {type:'affirm',text:`목소리 크기를 조절하는 것은 연습하면 점점 잘할 수 있습니다.`},
      {type:'affirm',text:`${n}은(는) 어디에서 어떤 목소리를 쓰는지 배우고 있습니다.`},
    ] },
  { id:'special-room', icon:'🏫', name:'특별실 이용하기', desc:'음악실·미술실·체육관 등에서 적절히 행동', fn:'회피/탈출 / 감각자극',
    gen:(n)=>[
      {type:'desc',text:`학교에는 교실 말고도 다른 공간이 있습니다.`},
      {type:'desc',text:`음악실, 미술실, 체육관, 컴퓨터실 같은 곳을 특별실이라고 합니다.`},
      {type:'desc',text:`특별실마다 사용하는 도구와 규칙이 다릅니다.`},
      {type:'persp',text:`특별실의 새로운 도구나 환경이 낯설게 느껴질 수 있습니다. 이것은 자연스러운 일입니다.`},
      {type:'coach',text:`${n}은(는) 특별실에 도착하면 먼저 선생님의 안내를 들어 볼 수 있습니다.`},
      {type:'desc',text:`특별실에서는 선생님이 알려주는 도구만 사용합니다.`},
      {type:'coach',text:`다른 도구가 만져 보고 싶으면 "이거 만져 봐도 돼요?"라고 물어볼 수 있습니다.`},
      {type:'persp',text:`규칙을 지키면 선생님은 안심하고, 친구들도 편안하게 활동할 수 있습니다.`},
      {type:'desc',text:`특별실 활동이 끝나면 도구를 정리하고 교실로 돌아갑니다.`},
      {type:'affirm',text:`${n}은(는) 여러 특별실에서 지내는 방법을 배우고 있습니다.`},
    ] },
  { id:'lunchtime', icon:'🍽', name:'급식 시간', desc:'급식실에서 적절히 행동', fn:'감각자극 / 회피/탈출',
    gen:(n)=>[
      {type:'desc',text:`학교에서는 점심시간에 급식실에서 밥을 먹습니다.`},
      {type:'desc',text:`급식실에는 많은 친구들이 함께 있어서 소리가 클 수 있습니다.`},
      {type:'persp',text:`시끄럽거나 냄새가 강하면 불편하다고 느끼는 사람도 있습니다.`},
      {type:'affirm',text:`불편한 느낌이 드는 것은 자연스러운 일입니다.`},
      {type:'coach',text:`${n}은(는) 소리가 너무 크게 느껴지면 귀마개를 사용해 볼 수 있습니다.`},
      {type:'desc',text:`자기 자리에 앉아서 먹고, 다 먹으면 식판을 정리합니다.`},
      {type:'coach',text:`먹기 싫은 반찬이 있으면 "이건 안 먹을래요"라고 조용히 말해 볼 수 있습니다.`},
      {type:'persp',text:`자리에 앉아서 먹으면 선생님은 안심합니다.`},
      {type:'desc',text:`급식 시간이 끝나면 교실로 돌아갑니다.`},
      {type:'affirm',text:`${n}은(는) 급식 시간을 잘 보내는 방법을 배우고 있습니다.`},
    ] },
  { id:'losing-play', icon:'🎲', name:'놀이에서 지기', desc:'놀이에서 졌을 때 적절히 반응', fn:'실물획득 / 관심끌기',
    gen:(n)=>[
      {type:'desc',text:`친구들과 놀이를 하면 이길 때도 있고 질 때도 있습니다.`},
      {type:'desc',text:`모든 사람이 항상 이기는 것은 아닙니다.`},
      {type:'persp',text:`놀이에서 지면 속상하거나 화가 나는 마음이 들 수 있습니다.`},
      {type:'affirm',text:`이런 마음이 드는 것은 자연스러운 일입니다.`},
      {type:'persp',text:`이긴 친구는 기분이 좋을 수 있습니다. 친구의 기쁨을 함께 나누면 좋아합니다.`},
      {type:'coach',text:`${n}은(는) 놀이에서 지면 "잘했어" 또는 "다음에 다시 하자"라고 말해 볼 수 있습니다.`},
      {type:'coach',text:`속상한 마음이 클 때는 잠깐 심호흡을 해 볼 수 있습니다.`},
      {type:'persp',text:`지고 나서도 침착하게 행동하면 친구들은 ${n}과(와) 또 놀고 싶어 합니다.`},
      {type:'desc',text:`다음에 놀이를 하면 이길 기회가 또 있습니다.`},
      {type:'affirm',text:`지는 것을 받아들이는 연습은 점점 쉬워질 수 있습니다.`},
    ] },
  { id:'spitting', icon:'💧', name:'침 뱉지 않기', desc:'침 뱉기 대신 적절한 행동', fn:'감각자극 / 관심끌기',
    gen:(n)=>[
      {type:'desc',text:`사람의 입 안에는 침(타액)이 있습니다.`},
      {type:'desc',text:`침은 보통 입 안에 있거나 삼킵니다.`},
      {type:'persp',text:`다른 사람에게 침을 뱉으면 그 사람은 불쾌하고 속상하다고 느낍니다.`},
      {type:'persp',text:`바닥이나 물건에 침을 뱉으면 주변 사람들이 불편해합니다.`},
      {type:'desc',text:`학교에서는 침을 뱉지 않습니다.`},
      {type:'coach',text:`${n}은(는) 침을 뱉고 싶은 느낌이 들면 침을 삼켜 볼 수 있습니다.`},
      {type:'coach',text:`입에 뭔가 느껴지면 물을 마시거나 휴지를 사용해 볼 수 있습니다.`},
      {type:'persp',text:`침을 뱉지 않으면 친구들과 선생님은 편안하게 느낍니다.`},
      {type:'affirm',text:`침을 삼키는 것은 연습할 수 있는 기술입니다.`},
      {type:'affirm',text:`${n}은(는) 입을 깨끗하게 관리하는 방법을 배우고 있습니다.`},
    ] },
  { id:'refuse', icon:'🚫', name:'거절 수용하기', desc:'"안 돼"를 들었을 때 적절히 반응', fn:'실물획득',
    gen:(n)=>[
      {type:'desc',text:`사람들은 무언가를 하고 싶거나 갖고 싶을 때가 있습니다.`},
      {type:'desc',text:`하지만 원하는 것을 항상 바로 할 수 있는 것은 아닙니다.`},
      {type:'desc',text:`선생님이나 부모님이 "지금은 안 돼"라고 말할 때가 있습니다.`},
      {type:'persp',text:`"안 돼"를 들으면 실망하거나 화가 날 수 있습니다. 이 마음은 자연스러운 것입니다.`},
      {type:'persp',text:`어른들이 "안 돼"라고 하는 것은 지금 그것이 어렵거나 위험하기 때문입니다.`},
      {type:'coach',text:`${n}은(는) "안 돼"를 들으면 "네, 알겠습니다"라고 말해 볼 수 있습니다.`},
      {type:'coach',text:`속상하면 심호흡을 하거나 다른 활동을 찾아 볼 수 있습니다.`},
      {type:'desc',text:`"지금은 안 돼"라고 해도 나중에 할 수 있는 경우도 있습니다.`},
      {type:'coach',text:`"그러면 언제 할 수 있어요?"라고 물어볼 수도 있습니다.`},
      {type:'affirm',text:`"안 돼"를 받아들이는 것은 연습하면 점점 쉬워질 수 있습니다.`},
    ] },
  { id:'elopement', icon:'🚧', name:'학교 안에 있기', desc:'학교 밖으로 나가지 않고 안전하게 지내기', fn:'회피/탈출 / 감각자극',
    gen:(n)=>[
      {type:'desc',text:`학교에는 건물과 운동장이 있고, 그 둘레에는 울타리(담장)가 있습니다.`},
      {type:'desc',text:`학생들은 수업 시간과 쉬는 시간에 학교 안에서 지냅니다.`},
      {type:'desc',text:`학교 밖에는 차가 다니는 도로와 여러 위험한 것들이 있습니다.`},
      {type:'persp',text:`때때로 교실이나 학교가 답답하거나 힘들게 느껴질 수 있습니다. 이런 마음은 자연스러운 것입니다.`},
      {type:'persp',text:`${n}이(가) 학교 밖으로 나가면 선생님과 부모님은 매우 걱정합니다.`},
      {type:'persp',text:`선생님은 ${n}이(가) 안전한지 확인할 수 없어서 불안합니다.`},
      {type:'desc',text:`밖에 나가고 싶은 마음이 들 때 할 수 있는 다른 방법이 있습니다.`},
      {type:'coach',text:`${n}은(는) 힘들 때 선생님에게 "밖에 나가고 싶어요"라고 말해 볼 수 있습니다.`},
      {type:'coach',text:`교실이 답답할 때 쉼 공간에서 잠깐 쉬는 것을 요청해 볼 수 있습니다.`},
      {type:'desc',text:`선생님이 허락하면 선생님과 함께 운동장이나 복도를 걸을 수 있습니다.`},
      {type:'affirm',text:`학교 안에는 ${n}이(가) 안전하게 쉴 수 있는 장소가 있습니다.`},
      {type:'affirm',text:`${n}은(는) 학교 안에서 안전하게 지내는 방법을 배우고 있습니다.`},
    ] },
  { id:'accidental-bump', icon:'💥', name:'실수로 부딪혔을 때', desc:'친구가 의도 없이 부딪혔을 때 반응', fn:'감각자극 / 관심끌기',
    gen:(n)=>[
      {type:'desc',text:`학교에는 많은 사람들이 함께 지내기 때문에 좁은 곳도 있습니다.`},
      {type:'desc',text:`복도, 교실, 급식실 같은 곳에서 사람들이 지나다니다 보면 몸이 부딪힐 수 있습니다.`},
      {type:'desc',text:`대부분의 부딪힘은 실수입니다. 일부러 한 것이 아닙니다.`},
      {type:'persp',text:`실수로 부딪힌 친구도 당황하거나 미안하다고 느낄 수 있습니다.`},
      {type:'persp',text:`부딪히면 아프거나 깜짝 놀랄 수 있습니다. 이것은 자연스러운 반응입니다.`},
      {type:'affirm',text:`놀라거나 불편한 느낌이 드는 것은 괜찮습니다.`},
      {type:'coach',text:`${n}은(는) 부딪혔을 때 먼저 "실수인가?"라고 생각해 볼 수 있습니다.`},
      {type:'desc',text:`실수로 부딪혔을 때 사람들은 보통 "괜찮아" 또는 "아, 미안"이라고 말합니다.`},
      {type:'coach',text:`아프면 선생님에게 "친구가 부딪혀서 아파요"라고 말해 볼 수 있습니다.`},
      {type:'persp',text:`침착하게 반응하면 친구는 고맙다고 느끼고, 선생님도 안심합니다.`},
      {type:'affirm',text:`실수와 일부러 한 것을 구별하는 것은 연습하면 점점 잘할 수 있습니다.`},
    ] },
  { id:'attention-seeking', icon:'👀', name:'적절하게 관심 받기', desc:'적절한 방법으로 관심을 받기', fn:'관심끌기',
    gen:(n)=>[
      {type:'desc',text:`사람들은 다른 사람의 관심을 받고 싶을 때가 있습니다.`},
      {type:'desc',text:`관심을 받고 싶은 마음은 누구에게나 있는 자연스러운 마음입니다.`},
      {type:'affirm',text:`${n}이(가) 관심을 받고 싶은 것은 당연한 일입니다.`},
      {type:'desc',text:`관심을 받는 방법에는 여러 가지가 있습니다.`},
      {type:'persp',text:`큰 소리를 내거나 물건을 던지면 주변 사람들은 놀라거나 불편하다고 느낍니다.`},
      {type:'persp',text:`그런 행동을 하면 선생님은 걱정이 되고, 친구들은 무섭다고 느낄 수 있습니다.`},
      {type:'desc',text:`사람들이 좋아하는 관심 받기 방법이 있습니다.`},
      {type:'coach',text:`${n}은(는) 선생님에게 이야기하고 싶을 때 손을 들거나 "선생님"이라고 불러 볼 수 있습니다.`},
      {type:'coach',text:`친구에게 이야기하고 싶을 때 "같이 놀자" 또는 "이것 봐"라고 말해 볼 수 있습니다.`},
      {type:'persp',text:`적절하게 말을 걸면 선생님과 친구들은 기꺼이 ${n}의 이야기를 들으려고 합니다.`},
      {type:'affirm',text:`적절하게 관심을 받는 것은 연습할 수 있는 기술입니다.`},
      {type:'affirm',text:`${n}은(는) 좋은 방법으로 관심을 받는 연습을 하고 있습니다.`},
    ] },
  { id:'play-skills', icon:'🧩', name:'적절한 놀이 기술', desc:'친구들과 놀이할 때 적절히 참여', fn:'관심끌기 / 실물획득',
    gen:(n)=>[
      {type:'desc',text:`쉬는 시간이나 점심시간에 친구들과 놀이를 합니다.`},
      {type:'desc',text:`놀이에는 규칙이 있습니다. 규칙은 모든 사람이 즐겁게 놀기 위해 있습니다.`},
      {type:'persp',text:`친구들은 규칙을 지키면서 노는 것을 좋아합니다.`},
      {type:'desc',text:`놀이를 시작하려면 먼저 친구들에게 "나도 같이 해도 돼?"라고 물어봅니다.`},
      {type:'coach',text:`${n}은(는) 놀이에 들어가고 싶을 때 "같이 하자" 또는 "나도 끼워 줘"라고 말해 볼 수 있습니다.`},
      {type:'desc',text:`놀이 중에는 차례를 지키고, 친구의 이야기도 들어 줍니다.`},
      {type:'coach',text:`내 차례가 아닐 때는 기다리면서 친구가 하는 것을 지켜볼 수 있습니다.`},
      {type:'persp',text:`차례를 지키고 규칙을 따르면 친구들은 ${n}과(와) 계속 놀고 싶어 합니다.`},
      {type:'coach',text:`놀이가 재미없거나 힘들면 "나는 다른 거 할래"라고 말하고 다른 놀이를 찾아볼 수 있습니다.`},
      {type:'affirm',text:`친구들과 함께 노는 방법은 연습하면 점점 더 잘할 수 있습니다.`},
      {type:'affirm',text:`${n}은(는) 친구들과 즐겁게 노는 방법을 배우고 있습니다.`},
    ] },
  { id:'blank', icon:'✏️', name:'빈 양식', desc:'직접 처음부터 작성', fn:'-',
    gen:()=>[
      {type:'desc',text:''},{type:'desc',text:''},{type:'persp',text:''},{type:'coach',text:''},{type:'affirm',text:''},
    ] },
];

// Level 1 (그림중심) and Level 2 (짧은 문장) data
const LEVEL_DATA = {
  'wait-turn': {
    1:(n)=>[
      {type:'desc',text:`학교에서 활동할 때 차례가 있어요.`,img:true},
      {type:'desc',text:`한 명씩 해요.`,img:true},
      {type:'coach',text:`${n}도 앉아서 기다려 볼 수 있어요.`,img:true},
      {type:'affirm',text:`기다리면 내 차례가 와요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`학교에서 활동할 때 차례가 있어요.`},
      {type:'desc',text:`모두 한꺼번에 할 수 없어서 한 명씩 해요.`},
      {type:'persp',text:`차례를 지키면 친구들이 좋아해요.`},
      {type:'coach',text:`${n}은(는) 손을 무릎에 놓고 기다려 볼 수 있어요.`},
      {type:'desc',text:`기다리면 내 차례가 와요.`},
      {type:'affirm',text:`기다리는 건 연습하면 점점 쉬워져요.`},
    ],
  },
  'ask-help': {
    1:(n)=>[
      {type:'desc',text:`공부할 때 어려울 수 있어요.`,img:true},
      {type:'coach',text:`${n}은(는) "도와주세요" 말해 볼 수 있어요.`,img:true},
      {type:'persp',text:`선생님이 도와줘요.`,img:true},
      {type:'affirm',text:`도움을 요청하면 괜찮아요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`공부할 때 모르는 게 있을 수 있어요.`},
      {type:'persp',text:`어려우면 답답한 마음이 들 수 있어요.`},
      {type:'coach',text:`${n}은(는) 손을 들고 "도와주세요" 말해 볼 수 있어요.`},
      {type:'persp',text:`선생님은 기꺼이 도와주려고 해요.`},
      {type:'desc',text:`도움을 받으면 문제를 풀 수 있어요.`},
      {type:'affirm',text:`도움을 요청하는 건 용기 있는 거예요.`},
    ],
  },
  'transition': {
    1:(n)=>[
      {type:'desc',text:`학교에서 활동이 바뀔 때가 있어요.`,img:true},
      {type:'persp',text:`좋아하는 게 끝나면 아쉬워요.`,img:true},
      {type:'coach',text:`${n}은(는) 하던 걸 멈추고 다음 걸 해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`좋아하는 건 나중에 또 할 수 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`학교에서는 하루에 여러 활동을 해요.`},
      {type:'desc',text:`좋아하는 활동도 끝날 때가 있어요.`},
      {type:'persp',text:`그만두어야 할 때 아쉬운 마음이 들 수 있어요.`},
      {type:'coach',text:`${n}은(는) "정리하세요" 하면 천천히 멈춰 볼 수 있어요.`},
      {type:'coach',text:`일과표를 보면 다음에 뭘 하는지 알 수 있어요.`},
      {type:'affirm',text:`좋아하는 활동은 나중에 또 할 수 있어요.`},
    ],
  },
  'gentle-body': {
    1:(n)=>[
      {type:'desc',text:`학교에서 친구 몸을 부드럽게 해요.`,img:true},
      {type:'persp',text:`세게 하면 친구가 아파요.`,img:true},
      {type:'coach',text:`${n}은(는) 살살 해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`부드러우면 친구가 같이 놀고 싶어 해요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`학교에서 친구들과 가까이 있을 때가 있어요.`},
      {type:'persp',text:`세게 밀거나 치면 친구가 아프고 무서워요.`},
      {type:'persp',text:`아프면 같이 놀기 싫다고 느껴요.`},
      {type:'coach',text:`${n}은(는) 천천히 걷고 살살 해 볼 수 있어요.`},
      {type:'coach',text:`말하고 싶으면 이름을 불러 볼 수 있어요.`},
      {type:'affirm',text:`부드럽게 하면 친구가 같이 놀고 싶어 해요.`},
    ],
  },
  'loud-voice': {
    1:(n)=>[
      {type:'desc',text:`교실에서는 작은 목소리로 말해요.`,img:true},
      {type:'desc',text:`운동장에서는 큰 목소리 괜찮아요.`,img:true},
      {type:'coach',text:`${n}은(는) 교실에서 작게 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`연습하면 점점 잘할 수 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`장소마다 맞는 목소리 크기가 있어요.`},
      {type:'desc',text:`교실에서는 작은 목소리, 운동장에서는 큰 목소리예요.`},
      {type:'persp',text:`교실에서 크게 말하면 친구들이 깜짝 놀라요.`},
      {type:'coach',text:`${n}은(는) 교실에서 옆 사람만 듣게 말해 볼 수 있어요.`},
      {type:'affirm',text:`목소리 크기 조절은 연습하면 잘할 수 있어요.`},
    ],
  },
  'special-room': {
    1:(n)=>[
      {type:'desc',text:`학교에 음악실, 체육관 같은 특별실이 있어요.`,img:true},
      {type:'coach',text:`특별실에 가면 선생님 말씀을 먼저 들어요.`,img:true},
      {type:'coach',text:`${n}은(는) 만져 보고 싶으면 물어볼 수 있어요.`,img:true},
      {type:'affirm',text:`끝나면 정리하고 교실로 가요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`학교에 음악실, 미술실, 체육관 같은 특별실이 있어요.`},
      {type:'desc',text:`특별실마다 도구와 규칙이 달라요.`},
      {type:'coach',text:`${n}은(는) 도착하면 선생님 안내를 먼저 들어 볼 수 있어요.`},
      {type:'coach',text:`다른 도구가 궁금하면 "만져도 돼요?" 물어볼 수 있어요.`},
      {type:'persp',text:`규칙을 지키면 선생님이 안심하고 친구들도 편해요.`},
      {type:'affirm',text:`${n}은(는) 특별실에서 지내는 방법을 배우고 있어요.`},
    ],
  },
  'lunchtime': {
    1:(n)=>[
      {type:'desc',text:`점심시간에 급식실에서 밥을 먹어요.`,img:true},
      {type:'coach',text:`${n}은(는) 자리에 앉아서 먹어 볼 수 있어요.`,img:true},
      {type:'coach',text:`싫은 반찬은 "안 먹을래요" 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`다 먹으면 식판을 정리해요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`점심시간에 급식실에서 밥을 먹어요.`},
      {type:'desc',text:`급식실에 사람이 많아서 소리가 클 수 있어요.`},
      {type:'persp',text:`시끄러우면 불편할 수 있어요. 괜찮은 거예요.`},
      {type:'coach',text:`${n}은(는) 자리에 앉아서 먹어 볼 수 있어요.`},
      {type:'coach',text:`싫은 반찬은 "이건 안 먹을래요" 말해 볼 수 있어요.`},
      {type:'affirm',text:`${n}은(는) 급식 시간을 잘 보내는 법을 배우고 있어요.`},
    ],
  },
  'losing-play': {
    1:(n)=>[
      {type:'desc',text:`친구와 놀이하면 질 때도 있어요.`,img:true},
      {type:'persp',text:`지면 속상한 마음이 들어요.`,img:true},
      {type:'coach',text:`${n}은(는) "다음에 또 하자" 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`다음에 놀면 이길 때도 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`친구와 놀이하면 이길 때도 있고 질 때도 있어요.`},
      {type:'persp',text:`놀이에서 지면 속상할 수 있어요.`},
      {type:'affirm',text:`속상한 건 자연스러운 거예요.`},
      {type:'coach',text:`${n}은(는) "잘했어" 또는 "다음에 하자" 말해 볼 수 있어요.`},
      {type:'coach',text:`속상하면 심호흡을 해 볼 수 있어요.`},
      {type:'affirm',text:`연습하면 점점 쉬워져요.`},
    ],
  },
  'spitting': {
    1:(n)=>[
      {type:'desc',text:`입 안에 침이 있으면 삼켜요.`,img:true},
      {type:'persp',text:`침을 뱉으면 사람들이 싫어해요.`,img:true},
      {type:'coach',text:`${n}은(는) 꿀꺽 삼켜 볼 수 있어요.`,img:true},
      {type:'affirm',text:`삼키는 건 연습할 수 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`입 안에 침이 있으면 보통 삼켜요.`},
      {type:'persp',text:`사람에게 침을 뱉으면 그 사람이 싫어하고 속상해요.`},
      {type:'coach',text:`${n}은(는) 뱉고 싶은 느낌이 들면 삼켜 볼 수 있어요.`},
      {type:'coach',text:`물을 마시거나 휴지를 써 볼 수도 있어요.`},
      {type:'affirm',text:`침 삼키는 건 연습하면 잘할 수 있어요.`},
    ],
  },
  'refuse': {
    1:(n)=>[
      {type:'desc',text:`하고 싶어도 "안 돼" 할 때가 있어요.`,img:true},
      {type:'persp',text:`속상할 수 있어요. 괜찮아요.`,img:true},
      {type:'coach',text:`${n}은(는) "네" 하고 기다려 볼 수 있어요.`,img:true},
      {type:'affirm',text:`나중에 할 수 있을 때도 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`하고 싶은 게 있어도 "안 돼" 할 때가 있어요.`},
      {type:'persp',text:`"안 돼" 들으면 속상할 수 있어요. 자연스러운 거예요.`},
      {type:'coach',text:`${n}은(는) "네, 알겠어요" 말해 볼 수 있어요.`},
      {type:'coach',text:`속상하면 다른 활동을 찾아 볼 수 있어요.`},
      {type:'desc',text:`지금은 안 돼도 나중에 할 수 있을 때가 있어요.`},
      {type:'affirm',text:`"안 돼"를 받아들이는 건 연습하면 쉬워져요.`},
    ],
  },
  'elopement': {
    1:(n)=>[
      {type:'desc',text:`${n}은(는) 학교 안에서 지내요.`,img:true},
      {type:'desc',text:`학교 밖에는 차가 다녀서 위험해요.`,img:true},
      {type:'coach',text:`나가고 싶으면 선생님에게 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`학교 안에 쉴 수 있는 곳이 있어요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`${n}은(는) 수업 시간과 쉬는 시간에 학교 안에서 지내요.`},
      {type:'desc',text:`학교 밖에는 차가 다녀서 위험할 수 있어요.`},
      {type:'persp',text:`교실이 답답할 때가 있어요. 자연스러운 거예요.`},
      {type:'coach',text:`${n}은(는) 힘들 때 "나가고 싶어요" 말해 볼 수 있어요.`},
      {type:'coach',text:`쉼 공간에서 잠깐 쉬는 것을 요청해 볼 수 있어요.`},
      {type:'affirm',text:`학교 안에 ${n}이(가) 쉴 수 있는 안전한 곳이 있어요.`},
    ],
  },
  'accidental-bump': {
    1:(n)=>[
      {type:'desc',text:`학교에서 지나다니다 부딪힐 때가 있어요.`,img:true},
      {type:'desc',text:`대부분 실수예요. 일부러 한 게 아니에요.`,img:true},
      {type:'coach',text:`${n}은(는) "괜찮아" 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`아프면 선생님에게 말하면 돼요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`학교에 사람이 많아서 지나가다 부딪힐 수 있어요.`},
      {type:'desc',text:`대부분 실수예요. 일부러 한 게 아니에요.`},
      {type:'persp',text:`부딪힌 친구도 미안하다고 느껴요.`},
      {type:'persp',text:`부딪히면 아프거나 놀랄 수 있어요. 자연스러운 거예요.`},
      {type:'coach',text:`${n}은(는) "실수인가?" 생각해 보고 "괜찮아" 말해 볼 수 있어요.`},
      {type:'affirm',text:`아프면 선생님에게 말하면 돼요.`},
    ],
  },
  'attention-seeking': {
    1:(n)=>[
      {type:'desc',text:`${n}은(는) 관심받고 싶을 때가 있어요.`,img:true},
      {type:'coach',text:`선생님한테 "선생님!" 불러 볼 수 있어요.`,img:true},
      {type:'coach',text:`친구한테 "같이 놀자" 말해 볼 수 있어요.`,img:true},
      {type:'affirm',text:`말로 하면 들어줘요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`사람들은 다른 사람 관심을 받고 싶을 때가 있어요.`},
      {type:'affirm',text:`${n}이(가) 관심받고 싶은 건 당연한 거예요.`},
      {type:'persp',text:`큰 소리를 내거나 물건을 던지면 사람들이 놀라요.`},
      {type:'coach',text:`${n}은(는) 손을 들거나 "선생님" 불러 볼 수 있어요.`},
      {type:'coach',text:`친구에게 "같이 놀자" 말해 볼 수 있어요.`},
      {type:'persp',text:`말로 하면 기꺼이 들어줘요.`},
      {type:'affirm',text:`좋은 방법으로 관심 받는 걸 배우고 있어요.`},
    ],
  },
  'play-skills': {
    1:(n)=>[
      {type:'desc',text:`쉬는 시간에 친구와 놀이해요.`,img:true},
      {type:'coach',text:`${n}은(는) "같이 하자" 말해 볼 수 있어요.`,img:true},
      {type:'coach',text:`내 차례 아닐 때는 기다려요.`,img:true},
      {type:'affirm',text:`같이 놀면 즐거워요.`,img:true},
    ],
    2:(n)=>[
      {type:'desc',text:`쉬는 시간에 친구들과 놀이를 해요.`},
      {type:'desc',text:`놀이에는 규칙이 있어요. 모두 즐겁게 놀려고 있는 거예요.`},
      {type:'coach',text:`${n}은(는) 같이 놀고 싶으면 "나도 끼워 줘" 말해 볼 수 있어요.`},
      {type:'desc',text:`내 차례가 아닐 때는 기다려요.`},
      {type:'persp',text:`차례를 지키면 친구들이 또 놀고 싶어 해요.`},
      {type:'affirm',text:`같이 노는 방법은 연습하면 점점 잘해요.`},
    ],
  },
  'blank': {
    1:()=>[{type:'desc',text:'',img:true},{type:'coach',text:'',img:true},{type:'affirm',text:'',img:true}],
    2:()=>[{type:'desc',text:''},{type:'persp',text:''},{type:'coach',text:''},{type:'affirm',text:''}],
  },
};
